apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: car-agentic
resources:
  - namespace-config.yaml
  - gateway.yaml
  - orchestrator.yaml
  - execution-services.yaml
  - kafka-ha.yaml
  - ingress-network-kustomization.yaml
