IF DB_ID('CarOps') IS NULL
    CREATE DATABASE CarOps;
GO
USE CarOps;
GO
IF OBJECT_ID('dbo.Vehicles') IS NULL
CREATE TABLE dbo.Vehicles (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Vin NVARCHAR(17) NOT NULL UNIQUE,
    Make NVARCHAR(64) NOT NULL,
    Model NVARCHAR(64) NOT NULL,
    Year INT NOT NULL,
    CustomerId NVARCHAR(64) NOT NULL,
    Mileage INT NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    UpdatedAt DATETIMEOFFSET NULL
);
GO
IF OBJECT_ID('dbo.WorkOrders') IS NULL
CREATE TABLE dbo.WorkOrders (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    DealerId NVARCHAR(64) NOT NULL,
    VehicleId UNIQUEIDENTIFIER NOT NULL,
    CustomerId NVARCHAR(64) NOT NULL,
    Concern NVARCHAR(2000) NOT NULL,
    Status INT NOT NULL,
    ScheduledAt DATETIMEOFFSET NULL,
    TechnicianId NVARCHAR(64) NULL,
    EstimatedCost DECIMAL(18,2) NOT NULL DEFAULT 0,
    CreatedAt DATETIMEOFFSET NOT NULL,
    UpdatedAt DATETIMEOFFSET NULL
);
CREATE INDEX IX_WorkOrders_Dealer_Status ON dbo.WorkOrders (DealerId, Status);
GO
